// clang-format off
#define K_ID                key("id")
#define K_METHOD            key("method")
#define K_PARAMS            key("params")
#define K_ERROR             key("error")

#define K_RESULT            key("result")
#define K_IN3               key("in3")
#define K_PROOF             key("proof")
#define K_REQUEST_COUNT     key("requestCount")

#define K_NODES             key("nodes")
#define K_LAST_BLOCK_NUMBER key("lastBlockNumber")
#define K_CAPACITY          key("capacity")
#define K_INDEX             key("index")
#define K_DEPOSIT           key("deposit")
#define K_PROPS             key("props")
#define K_URL               key("url")
#define K_ADDRESS           key("address")

#define K_BLOCK             key("block")
#define K_BLOCK_HASH        key("blockHash")
#define K_BLOCK_NUMBER      key("blockNumber")
#define K_TX_INDEX          key("txIndex")
#define K_MERKLE_PROOF      key("merkleProof")
#define K_TX_PROOF          key("txProof")

#define K_MSG_HASH          key("msgHash")
#define K_R                 key("r")
#define K_S                 key("s")
#define K_V                 key("v")

#define K_NONCE             key("nonce")
#define K_GAS               key("gas")
#define K_GAS_PRICE         key("gasPrice")
#define K_GAS_LIMIT         key("gasLimit")
#define K_TO                key("to")
#define K_VALUE             key("value")
#define K_INPUT             key("input")
#define K_DATA              key("data")
#define K_STATUS            key("status")
#define K_ROOT              key("root")
#define K_CUMULATIVE_GAS_USED key("cumulativeGasUsed")
#define K_LOGS_BLOOM        key("logsBloom")
#define K_LOGS              key("logs")
#define K_TOPICS            key("topics")

#define K_SIGNATURES        key("signatures")

#define K_TRANSACTION_INDEX key("transactionIndex")
#define K_TRANSACTION_HASH  key("transactionHash")

#define K_HASH              key("hash")
#define K_NUMBER            key("number")
#define K_PARENT_HASH       key("parentHash")
#define K_SHA3_UNCLES       key("sha3Uncles")
#define K_MINER             key("miner")
#define K_AUTHOR            key("author")
#define K_COINBASE          key("coinbase")
#define K_STATE_ROOT        key("stateRoot")
#define K_TRANSACTIONS_ROOT key("transactionsRoot")
#define K_RECEIPTS_ROOT     key("receiptsRoot")
#define K_RECEIPT_ROOT      key("receiptRoot")
#define K_LOGS_BLOOM        key("logsBloom")
#define K_DIFFICULTY        key("difficulty")
#define K_GAS_LIMIT         key("gasLimit")
#define K_GAS_USED          key("gasUsed")
#define K_TIMESTAMP         key("timestamp")
#define K_EXTRA_DATA        key("extraData")
#define K_SEAL_FIELDS       key("sealFields")
#define K_MIX_HASH          key("mixHash")
#define K_TRANSACTIONS      key("transactions")

#define K_PUBLIC_KEY        key("publicKey")
#define K_CHAIN_ID          key("chainId")
#define K_RAW               key("raw")
#define K_FROM              key("from")
#define K_STANDARD_V        key("standardV")
