/*******************************************************************************
 * This file is part of the Incubed project.
 * Sources: https://github.com/slockit/in3-c
 * 
 * Copyright (C) 2018-2020 slock.it GmbH, Blockchains LLC
 * 
 * 
 * COMMERCIAL LICENSE USAGE
 * 
 * Licensees holding a valid commercial license may use this file in accordance 
 * with the commercial license agreement provided with the Software or, alternatively, 
 * in accordance with the terms contained in a written agreement between you and 
 * slock.it GmbH/Blockchains LLC. For licensing terms and conditions or further 
 * information please contact slock.it at in3@slock.it.
 * 	
 * Alternatively, this file may be used under the AGPL license as follows:
 *    
 * AGPL LICENSE USAGE
 * 
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free Software 
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY 
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 * [Permissions of this strong copyleft license are conditioned on making available 
 * complete source code of licensed works and modifications, which include larger 
 * works using a licensed work, under the same license. Copyright and license notices 
 * must be preserved. Contributors provide an express grant of patent rights.]
 * You should have received a copy of the GNU Affero General Public License along 
 * with this program. If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/

// defines the chainspecs as rlp encoded values for different chains
// this file is autogenerated with the update_chainspec.sh script. Please don't edit it!

#define CHAINSPEC_KOVAN "\xf9\x01\xa4\x01*\x80\xe0\x80\x82\x00\x00\x83\x0f"                                                                                                                                                                                                    \
                        "B@\x82\x08\x00\x83MP\xf8\x82\x09\x0e\x83\x8c"                                                                                                                                                                                                         \
                        "a\x80\x82\x0b~\x83\x9c{a\x82\x0b>\xf9\x01}\x80\x01\xb8\xb4\x00\xd6\xcc\x1b\xa9\xcf\x89\xbd.X\x00\x97"                                                                                                                                                 \
                        "A\xf4\xf7"                                                                                                                                                                                                                                            \
                        "2[\xad\xc0\xed\x00"                                                                                                                                                                                                                                   \
                        "B\x7f\xea\xe2"                                                                                                                                                                                                                                        \
                        "A\x9c\x15\xb8\x9d\x1c!\xaf\x10\xd1\xb6"                                                                                                                                                                                                               \
                        "e\x0aM=N\xd9\xb0\x8e"                                                                                                                                                                                                                                 \
                        "cT\xc7\x0f\xe6\xf8\xcb\x04\x11\xb0\xd3$kBMl\x00 \xeeK\xe0\xe2\x02}v`<\xb7Q\xee\x06\x95\x19\xba\x81\xa1\x00\x10\xf9K)j\x85*\xaa\xc5.\xa6\xc5\xacr\xe0:\xfd\x03-\x00w3\xa1\xfei\xcf?,\xf9\x89\xf8\x1c{L\xac\x16\x93"                                    \
                        "8z\x00\xe6\xd2\xb9"                                                                                                                                                                                                                                   \
                        "1\xf5Z?\x17\x01\xc7"                                                                                                                                                                                                                                  \
                        "8\x9dY*wx\x89xy\x00\xe4\xa1\x06P\xe5\xa6\xd6\x00\x1c"                                                                                                                                                                                                 \
                        "8\xff\x8e"                                                                                                                                                                                                                                            \
                        "d\xf9p\x16\xa1"                                                                                                                                                                                                                                       \
                        "d\x5c\x00\xa0\xa2K\x9f\x0e^\xc7\xaaLs\x89\xb8"                                                                                                                                                                                                        \
                        "0/\xd0\x12"                                                                                                                                                                                                                                           \
                        "1\x94\xde\x80\x83\xa7>8\x01\xb8<\x00\xd6\xcc\x1b\xa9\xcf\x89\xbd.X\x00\x97"                                                                                                                                                                           \
                        "A\xf4\xf7"                                                                                                                                                                                                                                            \
                        "2[\xad\xc0\xed\x00\x10\xf9K)j\x85*\xaa\xc5.\xa6\xc5\xacr\xe0:\xfd\x03-\x00\xa0\xa2K\x9f\x0e^\xc7\xaaLs\x89\xb8"                                                                                                                                       \
                        "0/\xd0\x12"                                                                                                                                                                                                                                           \
                        "1\x94\xde\x80\x83\xa7>t\x01\xb8"                                                                                                                                                                                                                      \
                        "d\xfa\xad\xfa\xce?\xbd\x81\xce"                                                                                                                                                                                                                       \
                        "7\xb0\xe1\x9c\x0b"                                                                                                                                                                                                                                    \
                        "e\xff"                                                                                                                                                                                                                                                \
                        "B4\x14\x81"                                                                                                                                                                                                                                           \
                        "2Yn\x82!\xa3\x0b\xfen~\xffg\xfe\xe6"                                                                                                                                                                                                                  \
                        "d\xa0\x1cs\xba<V\xa4\xdf%^\xcf\x08\xbb\xf2\xc2\x80U\xc6R%\xc9\xa9\x84z\xbd\x94\x03\x80\x1e\xfb\x0e\xfe*%\xed\xe5\xdd:\x00:\xe8\x80\xc0).M\xd0_tx\xc6\xaa\x10x\x12X\xc5\xcc\x8bO8_\xc8\xfa\x98\x9c\x94\xaeq\x80|\x1b\x0a\x09<\xb1T{h-\xc7\x83\x16\xd9" \
                        "E\xc9\xb8"
#define CHAINSPEC_MAINNET "\xe9\x01\x01\x80\xe0\x80\x82\x00\x00\x83%\x95\x18\x82\x04\x00\x83(\xd1" \
                          "8\x82\x1c\x00\x83"                                                      \
                          "B\xaeP\x82\x1d\x0e\x83o\x15\x80\x82\x1f>\xc4\x80\x80\x80\x80"
#define CHAINSPEC_GOERLI "\xe1\x01\x05\x80\xc4\x80\x82\x1f>\xd8\x80\x02\x94\xe0\xa2\xbd" \
                         "BX\xd2v\x88"                                                   \
                         "7\xba\xa2j(\xfeq\xdc\x07\x9f\x84\xc7\x80"
