/*******************************************************************************
 * This file is part of the Incubed project.
 * Sources: https://github.com/slockit/in3-c
 * 
 * Copyright (C) 2018-2020 slock.it GmbH, Blockchains LLC
 * 
 * 
 * COMMERCIAL LICENSE USAGE
 * 
 * Licensees holding a valid commercial license may use this file in accordance 
 * with the commercial license agreement provided with the Software or, alternatively, 
 * in accordance with the terms contained in a written agreement between you and 
 * slock.it GmbH/Blockchains LLC. For licensing terms and conditions or further 
 * information please contact slock.it at in3@slock.it.
 * 	
 * Alternatively, this file may be used under the AGPL license as follows:
 *    
 * AGPL LICENSE USAGE
 * 
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free Software 
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY 
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 * [Permissions of this strong copyleft license are conditioned on making available 
 * complete source code of licensed works and modifications, which include larger 
 * works using a licensed work, under the same license. Copyright and license notices 
 * must be preserved. Contributors provide an express grant of patent rights.]
 * You should have received a copy of the GNU Affero General Public License along 
 * with this program. If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/

// defines the chainspecs as rlp encoded values for different chains
// this file is autogenerated with the update_chainspec.sh script. Please don't edit it!

#define CHAINSPEC_MAINNET "\xe9\x01\x01\x80\xe0\x80\x82\x00\x00\x83%\x95\x18\x82\x04\x00\x83(\xd1" \
                          "8\x82\x1c\x00\x83"                                                      \
                          "B\xaeP\x82\x1d\x0e\x83o\x15\x80\x82\x1f>\xc4\x80\x80\x80\x80"
#define CHAINSPEC_GOERLI "\xe1\x01\x05\x80\xc4\x80\x82\x1f>\xd8\x80\x02\x94\xe0\xa2\xbd" \
                         "BX\xd2v\x88"                                                   \
                         "7\xba\xa2j(\xfeq\xdc\x07\x9f\x84\xc7\x80"
