/*******************************************************************************
 * This file is part of the Incubed project.
 * Sources: https://github.com/slockit/in3-c
 *
 * Copyright (C) 2018-2022 slock.it GmbH, Blockchains LLC
 *
 *
 * COMMERCIAL LICENSE USAGE
 *
 * Licensees holding a valid commercial license may use this file in accordance
 * with the commercial license agreement provided with the Software or, alternatively,
 * in accordance with the terms contained in a written agreement between you and
 * slock.it GmbH/Blockchains LLC. For licensing terms and conditions or further
 * information please contact slock.it at in3@slock.it.
 *
 * Alternatively, this file may be used under the AGPL license as follows:
 *
 * AGPL LICENSE USAGE
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 * [Permissions of this strong copyleft license are conditioned on making available
 * complete source code of licensed works and modifications, which include larger
 * works using a licensed work, under the same license. Copyright and license notices
 * must be preserved. Contributors provide an express grant of patent rights.]
 * You should have received a copy of the GNU Affero General Public License along
 * with this program. If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/

// ::: This is a autogenerated file. Do not edit it manually! :::

#include "pk-signer_rpc.h"

#include "../../core/client/keys.h"
#include "../../core/client/plugin.h"
#include "../../core/client/request_internal.h"
#include "../../core/util/debug.h"
#include "../../core/util/log.h"
#include "../../core/util/mem.h"
#include "../../core/util/utils.h"

/**
 * adds a raw private key as signer, which allows signing transactions.
 */
static in3_ret_t handle_in3_addRawKey(in3_rpc_handle_ctx_t* ctx) {
  bytes_t pk;
  char*   curve;

  TRY_PARAM_GET_REQUIRED_BYTES(pk, ctx, 0, 32, 32)
  TRY_PARAM_GET_STRING(curve, ctx, 1, NULL)
  RPC_ASSERT(d_len(ctx->params) <= 2, "%s only accepts %u arguments.", "in3_addRawKey", 2);

  return in3_addRawKey(ctx, pk, curve);
}

/**
 * decrypts a JSON Keystore file as defined in the [Web3 Secret Storage Definition](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition) and adds it as signer.
 */
static in3_ret_t handle_in3_addJsonKey(in3_rpc_handle_ctx_t* ctx) {
  d_token_t* key;
  char*      passphrase;

  TRY_PARAM_GET_REQUIRED_OBJECT(key, ctx, 0)
  TRY_PARAM_GET_REQUIRED_STRING(passphrase, ctx, 1)
  RPC_ASSERT(d_len(ctx->params) <= 2, "%s only accepts %u arguments.", "in3_addJsonKey", 2);

  return in3_addJsonKey(ctx, key, passphrase);
}

/**
 * adds a signer from a mnemomic phrase
 */
static in3_ret_t handle_in3_addMnemonic(in3_rpc_handle_ctx_t* ctx) {
  char*      mnemomic;
  char*      passphrase;
  d_token_t* derivation;
  char*      curve;

  TRY_PARAM_GET_REQUIRED_STRING(mnemomic, ctx, 0)
  TRY_PARAM_GET_STRING(passphrase, ctx, 1, NULL)
  TRY_PARAM_GET_ARRAY(derivation, ctx, 2)
  TRY_PARAM_GET_STRING(curve, ctx, 3, "secp256k1")
  RPC_ASSERT(d_len(ctx->params) <= 4, "%s only accepts %u arguments.", "in3_addMnemonic", 4);

  return in3_addMnemonic(ctx, mnemomic, passphrase, derivation, curve);
}

/**
 * handle rpc-requests and delegate execution
 */
in3_ret_t pk_signer_rpc(in3_rpc_handle_ctx_t* ctx) {

#if !defined(RPC_ONLY) || defined(RPC_IN3_ADDRAWKEY)
  TRY_RPC("in3_addRawKey", handle_in3_addRawKey(ctx))
#endif

#if !defined(RPC_ONLY) || defined(RPC_IN3_ADDJSONKEY)
  TRY_RPC("in3_addJsonKey", handle_in3_addJsonKey(ctx))
#endif

#if !defined(RPC_ONLY) || defined(RPC_IN3_ADDMNEMONIC)
  TRY_RPC("in3_addMnemonic", handle_in3_addMnemonic(ctx))
#endif

#if !defined(RPC_ONLY) || defined(RPC_SIGNER_IDS)
  TRY_RPC("signer_ids", signer_ids(ctx))
#endif

#if !defined(RPC_ONLY) || defined(RPC_ETH_ACCOUNTS)
  TRY_RPC("eth_accounts", eth_accounts(ctx))
#endif

  return IN3_EIGNORE;
}