/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0 */

#include "ipfs.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Data, Data, AUTO)

PB_BIND(PBLink, PBLink, AUTO)

PB_BIND(PBNode, PBNode, AUTO)
