#!/bin/sh
REPO="https://raw.githubusercontent.com/paritytech/parity-ethereum/master/ethcore/res/ethereum"
CHAIN_H=../src/verifier/eth1/nano/chains.h
KOVAN_VALIDATORS=0xfaadface3fbd81ce37b0e19c0b65ff4234148132596e8221a30bfe6e7eff67fee664a01c73ba3c56a4df255ecf08bbf2c28055c65225c9a9847abd9403801efb0efe2a25ede5dd3a003ae880c0292e4dd05f7478c6aa10781258c5cc8b4f385fc8fa989c

echo "// defines the chainspecs as rlp encoded values for different chains"  > $CHAIN_H
echo "// this file is autogenerated with the update_chainspec.sh script. Please don't edit it!\n"  >> $CHAIN_H
curl -s $REPO/kovan.json      | in3 chainspec -name KOVAN -validators $KOVAN_VALIDATORS  >> $CHAIN_H
curl -s $REPO/foundation.json | in3 chainspec -name MAINNET >> $CHAIN_H
curl -s $REPO/goerli.json     | in3 chainspec -name GOERLI  >> $CHAIN_H

